# Supabase Configuration for AutaMedica Platform

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://autamedica-web-app.pages.dev"
additional_redirect_urls = [
  "https://autamedica-web-app.pages.dev/**",
  "https://autamedica-patients.pages.dev/**",
  "https://autamedica-doctors.pages.dev/**",
  "https://autamedica-companies.pages.dev/**",
  "http://localhost:3000/**",
  "http://localhost:4001/**",
  "http://localhost:4002/**"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = false
enable_manual_linking = false
enable_anonymous_sign_ins = false

[auth.email]
enable_confirmations = true

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[storage]
enabled = true

[realtime]
enabled = true
ip_version = "IPv4"

[functions]

[analytics]