version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "your-username" # Cambiar por tu usuario de GitHub
    assignees:
      - "your-username" # Cambiar por tu usuario de GitHub