name = "autamedica-auth"
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[env.production]
name = "autamedica-auth"

[env.preview]
name = "autamedica-auth-preview"
