name = "autamedica-web-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[pages]
compatibility_date = "2024-01-01"

# Dominios personalizados (estos se deben configurar manualmente en el dashboard)
# custom_domains = ["www.autamedica.com", "autamedica.com"]
