name = "autamedica-web-app"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = ".vercel/output/static"

# Routing configuration for SPA
[pages]
compatibility_date = "2024-01-01"

# Variables de entorno para producción (configurar en dashboard de Cloudflare Pages)
# Las variables NEXT_PUBLIC_* deben configurarse en el dashboard, no aquí
[env.production.vars]
NODE_ENV = "production"
SKIP_ENV_VALIDATION = "true"

# Dominios personalizados (configurar en el dashboard)
# custom_domains = ["www.autamedica.com", "autamedica.com"]
