name = "autamedica-web-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[pages]
compatibility_date = "2024-01-01"

# Variables de entorno para producción (configurar en dashboard de Cloudflare Pages)
[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://gtyvdircfhmdjiaelqkg.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0eXZkaXJjZmhtZGppYWVscWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Njc4NTUsImV4cCI6MjA3MjI0Mzg1NX0.DeEm08k7QOrKObWaz8AUaOB5N6Z2QZhZHFaUf2siALA"
NEXT_PUBLIC_NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://autamedica.com"
SKIP_ENV_VALIDATION = "true"

# Dominios personalizados (estos se deben configurar manualmente en el dashboard)
# custom_domains = ["www.autamedica.com", "autamedica.com"]
