-- Test fixture: casos avanzados con enums, identidad y quoted identifiers
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CREATE TYPE enums
CREATE TYPE user_status AS ENUM ('active', 'inactive', 'suspended');
CREATE TYPE priority_level AS ENUM ('low', 'medium', 'high', 'critical');

-- Test table with quoted identifiers and identity
CREATE TABLE public."UserProfiles" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" UUID NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    "firstName" VARCHAR NOT NULL,
    "lastName" VARCHAR NOT NULL,
    status user_status NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Test table with GENERATED ALWAYS
CREATE TABLE public.audit_trail (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id UUID NOT NULL,
    action VARCHAR NOT NULL,
    priority priority_level DEFAULT 'medium',
    metadata JSONB,
    tags TEXT[],
    ip_address INET,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    PRIMARY KEY (id)
);

-- Test table with composite primary key and quoted names
CREATE TABLE public."ProjectMembers" (
    "projectId" UUID NOT NULL,
    "memberId" UUID NOT NULL,
    role VARCHAR CHECK (role IN ('owner', 'admin', 'member', 'viewer')) DEFAULT 'member',
    permissions JSONB DEFAULT '{}',
    "joinedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    "lastActiveAt" TIMESTAMP,
    PRIMARY KEY ("projectId", "memberId")
);