name = "autamedica-patients"
compatibility_date = "2025-09-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "autamedica-patients"

[env.preview]
name = "autamedica-patients-preview"
