name = "autamedica-patients"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/dist"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
