#!/bin/bash

echo "🔧 CONFIGURACIÓN URGENTE DE SUPABASE OAUTH"
echo "=========================================="
echo ""
echo "El problema está claro: OAuth está retornando a la raíz (/) en lugar de /auth/callback"
echo ""
echo "📍 Ve AHORA a: https://supabase.com/dashboard/project/gtyvdircfhmdjiaelqkg/auth/url-configuration"
echo ""
echo "✅ ACTUALIZA estos campos:"
echo ""
echo "1️⃣ Site URL:"
echo "   https://autamedica-web-app.pages.dev"
echo ""
echo "2️⃣ Redirect URLs (CRÍTICO - añade TODAS):"
echo "   https://autamedica-web-app.pages.dev/auth/callback"
echo "   https://autamedica-web-app.pages.dev/"
echo "   http://localhost:3000/auth/callback"
echo ""
echo "3️⃣ En la pestaña 'Providers' > Google:"
echo "   - Asegúrate que esté habilitado"
echo "   - Client ID y Secret configurados"
echo "   - Redirect URL: https://gtyvdircfhmdjiaelqkg.supabase.co/auth/v1/callback"
echo ""
echo "⚠️  IMPORTANTE: Después de guardar los cambios en Supabase:"
echo "   1. Espera 30 segundos para que se propaguen"
echo "   2. Limpia caché del navegador (Ctrl+Shift+R)"
echo "   3. Intenta login de nuevo desde: https://autamedica-web-app.pages.dev/auth/login"
echo ""
echo "🎯 El token está llegando correctamente, solo necesitamos que Supabase"
echo "   redirija a /auth/callback en lugar de /"
echo ""