#!/bin/bash

echo "📝 Configuración de URLs de autenticación para Supabase"
echo "========================================================="
echo ""
echo "Por favor, ve a tu panel de Supabase y actualiza las siguientes URLs:"
echo ""
echo "1. Dashboard URL: https://supabase.com/dashboard/project/gtyvdircfhmdjiaelqkg/settings/auth"
echo ""
echo "2. En 'Authentication' > 'URL Configuration', actualiza:"
echo ""
echo "   Site URL:"
echo "   - Producción: https://autamedica-web-app.pages.dev"
echo "   - Desarrollo: http://localhost:3000"
echo ""
echo "   Redirect URLs (añade todas estas):"
echo "   - https://autamedica-web-app.pages.dev/auth/callback"
echo "   - https://autamedica-web-app.pages.dev/auth/callback-client"
echo "   - https://www.autamedica.com/auth/callback"
echo "   - https://autamedica.com/auth/callback"
echo "   - http://localhost:3000/auth/callback"
echo "   - http://localhost:3000/auth/callback-client"
echo ""
echo "3. En 'Authentication' > 'Providers':"
echo ""
echo "   Google OAuth:"
echo "   - Callback URL: https://gtyvdircfhmdjiaelqkg.supabase.co/auth/v1/callback"
echo ""
echo "   GitHub OAuth:"
echo "   - Callback URL: https://gtyvdircfhmdjiaelqkg.supabase.co/auth/v1/callback"
echo ""
echo "⚠️  IMPORTANTE: Asegúrate de guardar los cambios en Supabase"
echo ""
echo "URLs de las aplicaciones desplegadas:"
echo "- Web App: https://autamedica-web-app.pages.dev"
echo "- Doctors: https://autamedica-doctors.pages.dev"
echo "- Patients: https://autamedica-patients.pages.dev"
echo "- Companies: https://autamedica-companies.pages.dev"