name: Deploy Auth
on:
  push:
    branches: [main]
    paths:
      - "apps/auth/**"
      - "packages/**"
      - ".github/workflows/deploy-auth.yml"
  workflow_dispatch:
    inputs:
      reason:
        description: 'Deployment reason'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.15.2 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - name: Clean build artifacts
        working-directory: apps/auth
        run: |
          rm -rf .next .vercel .open-next node_modules/.cache
          echo "Build cache cleaned"
      - name: Build packages
        run: pnpm build:packages:core
      - name: Build Next for Cloudflare
        working-directory: apps/auth
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: pnpm dlx @cloudflare/next-on-pages@latest --experimental-minify
      - name: Deploy to Cloudflare Pages
        working-directory: apps/auth
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          # Deploy with cache bypass to force fresh build
          npx wrangler pages deploy .vercel/output/static \
            --project-name=autamedica-auth \
            --branch=main \
            --commit-dirty=true \
            --skip-caching
