name: 'Desplegar Preview (Pages)'

on:
  pull_request:
    branches: [ develop, staging ]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/desplegar-preview.yml'

jobs:
  preview:
    name: 'Preview por PR'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      PAGES_PROJECTS: autamedica-web-app,autamedica-patients,autamedica-doctors,autamedica-companies,autamedica-admin
    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Configurar PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Build monorepo (tolerante)
        run: |
          pnpm --filter @autamedica/web-app build || true
          pnpm --filter @autamedica/patients build || true
          pnpm --filter @autamedica/doctors build || true
          pnpm --filter @autamedica/companies build || true
          pnpm --filter @autamedica/admin build || true

      - name: Instalar Wrangler
        run: pnpm add -g wrangler

      - name: Desplegar previews por proyecto
        shell: bash
        run: |
          IFS=',' read -ra PROJS <<< "${PAGES_PROJECTS}"
          for p in "${PROJS[@]}"; do
            echo "→ Deploy preview: $p (rama ${{ github.head_ref }})"
            wrangler pages deploy . --project-name "$p" --branch "${{ github.head_ref }}" || true
          done