name: 'Desplegar Producción (Pages)'

on:
  push:
    branches: [ main ]

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  # ============================================
  # Job 1: Web-App (Landing + Auth)
  # ============================================
  deploy-web-app:
    name: 'Deploy Web-App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm build:packages:core

      - name: Build web-app
        working-directory: apps/web-app
        run: pnpm run build:cloudflare

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/web-app
        run: |
          wrangler pages deploy .vercel/output/static \
            --project-name autamedica-web-app \
            --branch main

  # ============================================
  # Job 2: Doctors Portal
  # ============================================
  deploy-doctors:
    name: 'Deploy Doctors'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm build:packages:core

      - name: Build doctors
        run: pnpm --filter @autamedica/doctors build

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/doctors
        run: |
          wrangler pages deploy .next \
            --project-name autamedica-doctors \
            --branch main

  # ============================================
  # Job 3: Companies Portal
  # ============================================
  deploy-companies:
    name: 'Deploy Companies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm build:packages:core

      - name: Build companies
        run: pnpm --filter @autamedica/companies build

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/companies
        run: |
          wrangler pages deploy .next \
            --project-name autamedica-companies \
            --branch main
