name: 'Desplegar Producción (Pages)'

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  # ============================================
  # Job 1: Web-App (Landing)
  # ============================================
  deploy-web-app:
    name: 'Deploy Web-App'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm run build:packages

      - name: Build Next.js for Cloudflare Pages
        working-directory: apps/web-app
        run: npx @cloudflare/next-on-pages@latest

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/web-app
        run: |
          wrangler pages deploy .vercel/output/static \
            --project-name autamedica-web-app \
            --branch production

  # ============================================
  # Job 2: Auth Hub (Autenticación Central)
  # ============================================
  deploy-auth:
    name: 'Deploy Auth'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm run build:packages

      - name: Build auth for Cloudflare Pages
        working-directory: apps/auth
        run: npx @cloudflare/next-on-pages@latest
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          AUTH_HUB_SECRET: ${{ secrets.AUTH_HUB_SECRET }}

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/auth
        run: |
          wrangler pages deploy .vercel/output/static \
            --project-name autamedica-auth \
            --branch production

  # ============================================
  # Job 3: Doctors Portal
  # ============================================
  deploy-doctors:
    name: 'Deploy Doctors'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm run build:packages

      - name: Build doctors with Next.js
        run: pnpm --filter @autamedica/doctors build

      - name: Adapt for Cloudflare Pages
        working-directory: apps/doctors
        run: npx @cloudflare/next-on-pages@latest

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/doctors
        run: |
          wrangler pages deploy .vercel/output/static \
            --project-name autamedica-doctors \
            --branch main

  # ============================================
  # Job 4: Companies Portal
  # ============================================
  deploy-companies:
    name: 'Deploy Companies'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages core
        run: pnpm run build:packages

      - name: Build companies with Next.js
        run: pnpm --filter @autamedica/companies build

      - name: Adapt for Cloudflare Pages
        working-directory: apps/companies
        run: npx @cloudflare/next-on-pages@latest

      - name: Install Wrangler
        run: pnpm add -g wrangler

      - name: Deploy to Cloudflare Pages
        working-directory: apps/companies
        run: |
          wrangler pages deploy .vercel/output/static \
            --project-name autamedica-companies \
            --branch main
