name: 'Desplegar Producción (Pages)'

on:
  push:
    branches: [ main ]

jobs:
  produccion:
    name: 'Deploy a Producción'
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      PAGES_PROJECTS: autamedica-web-app,autamedica-patients,autamedica-doctors,autamedica-companies,autamedica-admin
    steps:
      - uses: actions/checkout@v4

      - name: Configurar PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Build monorepo (tolerante)
        run: |
          pnpm --filter @autamedica/web-app build || true
          pnpm --filter @autamedica/patients build || true
          pnpm --filter @autamedica/doctors build || true
          pnpm --filter @autamedica/companies build || true
          pnpm --filter @autamedica/admin build || true

      - name: Instalar Wrangler
        run: pnpm add -g wrangler

      - name: Desplegar a Producción (main)
        shell: bash
        run: |
          IFS=',' read -ra PROJS <<< "${PAGES_PROJECTS}"
          for p in "${PROJS[@]}"; do
            echo "→ Deploy producción: $p"
            wrangler pages deploy . --project-name "$p" --branch "main" || true
          done